# Generated by Django 3.2.3 on 2021-08-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=70)),
                ('born', models.DateField(null=True)),
                ('cant', models.IntegerField()),
                ('rol', models.CharField(default='NORMAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked_by', to='Pokes_App.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes', to='Pokes_App.user')),
            ],
        ),
    ]
